Revert "Replace --privileged with more fine grained permissions"
Fails on:
```
Error: mount /var/lib/containers/storage/overlay:/var/lib/containers/storage/overlay, flags: 0x1000: permission denied
```

This reverts commit d1d2621f62f1ee31af5d156c316d10f5f198950b.